### ISSUE TITLE
Token-based authentication not work if service have space in name.

### ISSUE THREAD

**Issue by BigOHenry** [mortensteenrasmussen/docker-registry-manifest-cleanup#19]
Token-based authentication not work if service have space in name. Example: service="Service name with spaces"

version: master

docker registry config:
```
auth:
  token:
  realm: ""
  service: "Docker registry"
  issuer: ""
  rootcertbundle: ""
```

Thank you
